'use strict';

module.exports = {
  team: [
    'city',
    'conference',
    'division',
    'name',
    'logo_120x120',
    'logo_30x30',
    'logo_40x40',
    'logo_60x60',
    'primary_color',
    'secondary_color'
  ],
  player: {
    'player__first_name': 'firstName',
    'player__last_name': 'lastName',
    'player__number': 'number',
    'player__position': 'position'
  },
  game: [
    'defense_assists',
    'defense_forced_fumbles',
    'defense_misc_assists',
    'defense_misc_tackles',
    'defence_passes_defended',
    'defence_sack_yards',
    'defence_sp_assists',
    'defence_sp_tackles',
    'defence_stuff_yards',
    'defence_stuffs',
    'defence_tackles',
    'fg_attempted',
    'fg_blocked',
    'fg_distances',
    'fg_long',
    'fg_made',
    'fumble_fumbles',
    'fumble_lost_fumbles',
    'fumble_own_recovered',
    'fumble_own_recovered_td',
    'fumble_owm_recovered_yards',
    'interception_return_attempts',
    'interception_return_long',
    'interception_return_long_td',
    'interception_return_touchdowns',
    'interception_return_yards',
    'interceptions',
    'kick_return_long',
    'kick_return_long_td',
    'kick_return_touchdowns',
    'kick_return_yards',
    'kick_returns',
    'kickoffs',
    'kickoffs_end_zone',
    'kickoffs_touchback',
    'opponent_fumbles_recovered',
    'opponent_fumbles_td',
    'opponent_fumbles_yards',
    'passing_attempts',
    'passing_completions',
    'passing_interceptions',
    'passing_long',
    'passing_long_td',
    'passing_net_yards',
    'passing_sacked',
    'passing_touchdowns',
    'passing_yards',
    'passing_yards_lost',
    'penalty_penalties',
    'penalty_yards',
    'punt_return_long',
    'punt_return_long_td',
    'punt_return_touchdowns',
    'punt_return_yards',
    'punt_returns',
    'punting_inside_20',
    'punting_long',
    'punting_return_yards',
    'punting_returns',
    'punting_touchbacks',
    'punting_yards',
    'punts',
    'punts_blocked',
    'receiving_long',
    'receiving_long_td',
    'receiving_targets',
    'receiving_tds',
    'receiving_yards',
    'receptions',
    'return_total_touchdowns',
    'return_total_yards',
    'rushing_attempts',
    'rushing_long',
    'rushing_long_td',
    'rushing_touchdowns',
    'rushing_yards',
    'safeties',
    'two_point_conversions',
    'two_point_conversions_attempted',
    'xp_attempts',
    'xp_blocked',
    'xp_made'
  ]
};